package edu.kit.sdq.dsis.unified.design.services;

import java.util.*;

import org.eclipse.emf.ecore.EObject;

import edu.kit.sdq.dsis.unified.design.actions.RequirementTraceHelper;
import unified.*;

/**
 * Advanced Analysis Services - UPDATED for Requirements Support
 * Provides model analysis services including requirement metrics.
 *
 * All calls to metamodel methods that are not yet generated (getRequirements,
 * getRelatedBlocks, getRelatedHazards, getPriority, getRequirementType,
 * getRelatedRequirements) are routed through RequirementTraceHelper so that
 * this class compiles and runs correctly even before the EMF code generator
 * has been re-run.
 */
public class AdvancedAnalysisServices {

    // =========================================================================
    // ModelMetrics inner class
    // =========================================================================

    /**
     * Model Metrics - UPDATED to include requirement metrics.
     */
    public static class ModelMetrics {
        // Architecture Metrics
        private int totalBlocks;
        private int totalConnections;
        private int cyclomaticComplexity;
        private double averageBlockDegree;

        // Safety Metrics
        private int totalHazards;
        private double hazardCoverage;

        // FMEA Metrics
        private int totalFMEAItems;
        private double fmeaCoverage;
        private double averageRPN;
        private int highRiskItems;
        private double autoGeneratedPercentage;

        // Traceability Metrics
        private double traceabilityDensity;
        private int traceabilityLinks;

        // Quality Scores
        private int completenessScore;
        private int consistencyScore;

        // Requirement Metrics
        private int totalRequirements;
        private int functionalRequirements;
        private int safetyRequirements;
        private int performanceRequirements;
        private int highPriorityRequirements;
        private int mediumPriorityRequirements;
        private int lowPriorityRequirements;
        private int requirementsWithTraces;
        private double requirementCoverage;
        private double avgTracesPerRequirement;
        private int requirementToBlockLinks;
        private int requirementToHazardLinks;
        private int requirementToFMEALinks;

        // Getters - Architecture
        public int getTotalBlocks()            { return totalBlocks; }
        public int getTotalConnections()        { return totalConnections; }
        public int getCyclomaticComplexity()    { return cyclomaticComplexity; }
        public double getAverageBlockDegree()   { return averageBlockDegree; }

        // Getters - Safety
        public int getTotalHazards()            { return totalHazards; }
        public double getHazardCoverage()       { return hazardCoverage; }

        // Getters - FMEA
        public int getTotalFMEAItems()          { return totalFMEAItems; }
        public double getFmeaCoverage()         { return fmeaCoverage; }
        public double getAverageRPN()           { return averageRPN; }
        public int getHighRiskItems()           { return highRiskItems; }
        public double getAutoGeneratedPercentage() { return autoGeneratedPercentage; }

        // Getters - Traceability
        public double getTraceabilityDensity()  { return traceabilityDensity; }
        public int getTraceabilityLinks()       { return traceabilityLinks; }

        // Getters - Quality
        public int getCompletenessScore()       { return completenessScore; }
        public int getConsistencyScore()        { return consistencyScore; }

        // Getters - Requirements
        public int getTotalRequirements()            { return totalRequirements; }
        public int getFunctionalRequirements()        { return functionalRequirements; }
        public int getSafetyRequirements()            { return safetyRequirements; }
        public int getPerformanceRequirements()       { return performanceRequirements; }
        public int getHighPriorityRequirements()      { return highPriorityRequirements; }
        public int getMediumPriorityRequirements()    { return mediumPriorityRequirements; }
        public int getLowPriorityRequirements()       { return lowPriorityRequirements; }
        public int getRequirementsWithTraces()        { return requirementsWithTraces; }
        public double getRequirementCoverage()        { return requirementCoverage; }
        public double getAvgTracesPerRequirement()    { return avgTracesPerRequirement; }
        public int getRequirementToBlockLinks()       { return requirementToBlockLinks; }
        public int getRequirementToHazardLinks()      { return requirementToHazardLinks; }
        public int getRequirementToFMEALinks()        { return requirementToFMEALinks; }
    }

    // =========================================================================
    // computeModelMetrics
    // =========================================================================

    /**
     * Compute comprehensive model metrics including requirements.
     */
    public ModelMetrics computeModelMetrics(UnifiedSystemModel model) {
        ModelMetrics metrics = new ModelMetrics();

        // ---- Architecture Metrics ----
        metrics.totalBlocks      = model.getSystemBlocks().size() + model.getRootBlocks().size();
        metrics.totalConnections = model.getBlockConnections().size();

        int totalEdges = model.getBlockConnections().size();
        int totalNodes = metrics.totalBlocks;
        metrics.cyclomaticComplexity = totalEdges - totalNodes + 2;

        if (totalNodes > 0) {
            metrics.averageBlockDegree = (2.0 * totalEdges) / totalNodes;
        }

        // ---- Safety Metrics ----
        metrics.totalHazards = model.getGlobalHazards().size();

        int blocksWithHazards = 0;
        for (SafetyCriticalBlock block : model.getRootBlocks()) {
            for (IntegratedHazard hazard : model.getGlobalHazards()) {
                if (hazard.getRelatedBlocks().contains(block)) {
                    blocksWithHazards++;
                    break;
                }
            }
        }
        if (!model.getRootBlocks().isEmpty()) {
            metrics.hazardCoverage = (double) blocksWithHazards / model.getRootBlocks().size();
        }

        // ---- FMEA Metrics ----
        int totalFMEAItems = 0;
        int autoGenerated  = 0;
        double totalRPN    = 0;
        int highRisk       = 0;

        for (FMEAAnalysis analysis : model.getFmeaAnalysis()) {
            for (FMEAItem item : analysis.getFmeaItems()) {
                totalFMEAItems++;
                if (item.isAutoGenerated()) autoGenerated++;
                int rpn = item.getSeverity() * item.getOccurrence() * item.getDetection();
                totalRPN += rpn;
                if (rpn > 100) highRisk++;
            }
        }

        metrics.totalFMEAItems = totalFMEAItems;
        metrics.highRiskItems  = highRisk;

        if (totalFMEAItems > 0) {
            metrics.averageRPN              = totalRPN / totalFMEAItems;
            metrics.autoGeneratedPercentage = (autoGenerated * 100.0) / totalFMEAItems;
        }

        int blocksWithFMEA = 0;
        for (SafetyCriticalBlock block : model.getRootBlocks()) {
            outer:
            for (FMEAAnalysis analysis : model.getFmeaAnalysis()) {
                for (FMEAItem item : analysis.getFmeaItems()) {
                    if (item.getAnalyzedComponent() == block) {
                        blocksWithFMEA++;
                        break outer;
                    }
                }
            }
        }
        if (!model.getRootBlocks().isEmpty()) {
            metrics.fmeaCoverage = (double) blocksWithFMEA / model.getRootBlocks().size();
        }

        // ---- Requirement Metrics (via helper) ----
        List<Requirement> requirements = RequirementTraceHelper.getRequirements(model);
        metrics.totalRequirements = requirements.size();

        int totalTraceSum = 0;
        for (Requirement req : requirements) {

            // Count by type
            Object reqType = RequirementTraceHelper.getRequirementType(req);
            if (reqType != null) {
                String typeStr = reqType.toString();
                if (typeStr.equals("FUNCTIONAL"))   metrics.functionalRequirements++;
                else if (typeStr.equals("SAFETY"))  metrics.safetyRequirements++;
                else if (typeStr.equals("PERFORMANCE")) metrics.performanceRequirements++;
            }

            // Count by priority
            Object priority = RequirementTraceHelper.getPriority(req);
            if (priority != null) {
                String prioStr = priority.toString();
                if (prioStr.equals("HIGH"))        metrics.highPriorityRequirements++;
                else if (prioStr.equals("MEDIUM")) metrics.mediumPriorityRequirements++;
                else if (prioStr.equals("LOW"))    metrics.lowPriorityRequirements++;
            }

            // Count traces
            int blockLinks  = RequirementTraceHelper.getRelatedBlocks(req).size();
            int hazardLinks = RequirementTraceHelper.getRelatedHazards(req).size();
            int fmeaLinks   = RequirementTraceHelper.countFMEALinksForRequirement(model, req);

            metrics.requirementToBlockLinks  += blockLinks;
            metrics.requirementToHazardLinks += hazardLinks;
            metrics.requirementToFMEALinks   += fmeaLinks;

            int totalReqLinks = blockLinks + hazardLinks + fmeaLinks;
            totalTraceSum += totalReqLinks;
            if (totalReqLinks > 0) metrics.requirementsWithTraces++;
        }

        if (metrics.totalRequirements > 0) {
            metrics.requirementCoverage     = (double) metrics.requirementsWithTraces / metrics.totalRequirements;
            metrics.avgTracesPerRequirement = (double) totalTraceSum / metrics.totalRequirements;
        }

        // ---- Traceability Metrics ----
        metrics.traceabilityLinks =
            metrics.requirementToBlockLinks +
            metrics.requirementToHazardLinks +
            metrics.requirementToFMEALinks +
            countHazardToBlockLinks(model) +
            countFMEAToComponentLinks(model) +
            countFMEAToFailureModeLinks(model) +
            countFMEAToHazardLinks(model) +
            model.getBlockConnections().size();

        int possibleLinks = metrics.totalBlocks * (metrics.totalBlocks - 1) / 2;
        if (possibleLinks > 0) {
            metrics.traceabilityDensity = (double) metrics.traceabilityLinks / possibleLinks;
        }

        // ---- Completeness Score ----
        double architectureCompleteness = metrics.totalBlocks > 0
            ? Math.min(100, (metrics.totalConnections * 100.0) / metrics.totalBlocks) : 0;
        double safetyCompleteness       = metrics.hazardCoverage * 100;
        double fmeaCompleteness         = metrics.fmeaCoverage * 100;
        double requirementCompleteness  = metrics.requirementCoverage * 100;

        metrics.completenessScore = (int) (
            (architectureCompleteness + safetyCompleteness + fmeaCompleteness + requirementCompleteness) / 4);

        // ---- Consistency Score ----
        int consistencyIssues = 0;

        for (SafetyCriticalBlock block : model.getRootBlocks()) {
            if (!hasAssociatedHazards(block, model))              consistencyIssues++;
            if (requiresFMEAValidation(block) && !hasFMEAAnalysis(block, model)) consistencyIssues++;
        }

        // Requirement consistency: safety requirements must link to a hazard or FMEA item
        for (Requirement req : requirements) {
            Object reqType = RequirementTraceHelper.getRequirementType(req);
            if (reqType != null && reqType.toString().equals("SAFETY")) {
                if (RequirementTraceHelper.getRelatedHazards(req).isEmpty() &&
                    RequirementTraceHelper.countFMEALinksForRequirement(model, req) == 0) {
                    consistencyIssues++;
                }
            }
        }

        int maxIssues = Math.max(1, model.getRootBlocks().size() + requirements.size());
        metrics.consistencyScore = Math.max(0, 100 - (consistencyIssues * 100 / maxIssues));

        return metrics;
    }

    // =========================================================================
    // Public helper methods (called from Sirius services)
    // =========================================================================

    public boolean hasAssociatedHazards(SafetyCriticalBlock block, UnifiedSystemModel model) {
        for (IntegratedHazard hazard : model.getGlobalHazards()) {
            if (hazard.getRelatedBlocks().contains(block)) return true;
        }
        return false;
    }

    public boolean hasAssociatedHazards(SafetyCriticalBlock block) {
        UnifiedSystemModel model = getModel(block);
        return model != null && hasAssociatedHazards(block, model);
    }

    public boolean requiresFMEAValidation(SafetyCriticalBlock block) {
        return block.getSafetyCriticality() == SafetyCriticalityLevel.HIGH ||
               block.getSafetyCriticality() == SafetyCriticalityLevel.CRITICAL;
    }

    // =========================================================================
    // FMEA item generation
    // =========================================================================

    /**
     * Generates FMEA items for all safety-critical blocks that have failure modes.
     *
     * Note: ActionStatus.PENDING is used if available; if the enum literal name
     * differs in your metamodel, adjust the fallback branch below.
     */
    public List<FMEAItem> generateFMEAItems(UnifiedSystemModel model) {
        List<FMEAItem> items = new ArrayList<>();

        for (SafetyCriticalBlock block : model.getRootBlocks()) {
            for (BlockFailureMode fm : block.getFailureModes()) {
                FMEAItem item = UnifiedFactory.eINSTANCE.createFMEAItem();
                item.setName("FMEA: " + block.getName() + " - " + fm.getName());
                item.setId("FMEA_" + System.currentTimeMillis() + "_" + items.size());
                item.setAnalyzedComponent(block);
                item.setFailureMode(fm);
                item.setSeverity(estimateSeverity(block, fm));
                item.setOccurrence(estimateOccurrence(fm));
                item.setDetection(5);
                item.setAutoGenerated(true);
                item.setActionStatus(resolveDefaultActionStatus());

                items.add(item);
            }
        }

        return items;
    }

    /**
     * Resolves the default ActionStatus enum literal used when creating auto-generated
     * FMEA items. Tries PENDING first; falls back to the first available literal if
     * PENDING does not exist in this version of the metamodel.
     */
    private ActionStatus resolveDefaultActionStatus() {
        try {
            return ActionStatus.IN_PROGRESS;
        } catch (IllegalArgumentException | NullPointerException e) {
            // PENDING literal not present — use first available value as a safe default
            ActionStatus[] values = ActionStatus.values();
            return values.length > 0 ? values[0] : null;
        }
    }

    // =========================================================================
    // Recommendations
    // =========================================================================

    public enum RecommendationType {
        SAFETY_IMPROVEMENT,
        RISK_MITIGATION,
        HAZARD_MITIGATION,
        COMPLETENESS,
        CONSISTENCY,
        PERFORMANCE,
        REQUIREMENT_TRACEABILITY
    }

    public static class Recommendation {
        private final RecommendationType type;
        private final String description;

        public Recommendation(RecommendationType type, String description) {
            this.type        = type;
            this.description = description;
        }

        public RecommendationType getType()    { return type; }
        public String getDescription()          { return description; }
    }

    public List<Recommendation> generateRecommendations(UnifiedSystemModel model) {
        List<Recommendation> recommendations = new ArrayList<>();
        ModelMetrics metrics = computeModelMetrics(model);

        if (metrics.getCompletenessScore() < 50)
            recommendations.add(new Recommendation(RecommendationType.COMPLETENESS,
                "Model completeness is below 50%. Add more hazard associations, FMEA items, and traceability links."));

        if (metrics.getHazardCoverage() < 0.5)
            recommendations.add(new Recommendation(RecommendationType.HAZARD_MITIGATION,
                "Hazard coverage is below 50%. Link more hazards to safety-critical blocks."));

        if (metrics.getFmeaCoverage() < 0.8)
            recommendations.add(new Recommendation(RecommendationType.COMPLETENESS,
                "FMEA coverage is below 80%. Perform FMEA analysis on more safety-critical blocks."));

        if (metrics.getAverageRPN() > 100)
            recommendations.add(new Recommendation(RecommendationType.RISK_MITIGATION,
                "Average RPN exceeds 100. Review and mitigate high-risk FMEA items."));

        if (metrics.getTraceabilityDensity() < 0.3)
            recommendations.add(new Recommendation(RecommendationType.COMPLETENESS,
                "Traceability density is below 30%. Add more links between architecture and safety elements."));

        if (metrics.getRequirementCoverage() < 0.5)
            recommendations.add(new Recommendation(RecommendationType.REQUIREMENT_TRACEABILITY,
                "Requirement coverage is below 50%. Link requirements to blocks, hazards, and FMEA items."));

        // Safety requirements without hazard/FMEA links
        if (metrics.getSafetyRequirements() > 0) {
            int unlinkedSafety = 0;
            for (Requirement req : RequirementTraceHelper.getRequirements(model)) {
                Object reqType = RequirementTraceHelper.getRequirementType(req);
                if (reqType != null && reqType.toString().equals("SAFETY")) {
                    if (RequirementTraceHelper.getRelatedHazards(req).isEmpty() &&
                        RequirementTraceHelper.countFMEALinksForRequirement(model, req) == 0) {
                        unlinkedSafety++;
                    }
                }
            }
            if (unlinkedSafety > 0)
                recommendations.add(new Recommendation(RecommendationType.REQUIREMENT_TRACEABILITY,
                    unlinkedSafety + " safety requirement(s) are not linked to hazards or FMEA items."));
        }

        // High-priority requirements with insufficient traces
        if (metrics.getHighPriorityRequirements() > 0) {
            int underTraced = 0;
            for (Requirement req : RequirementTraceHelper.getRequirements(model)) {
                Object priority = RequirementTraceHelper.getPriority(req);
                if (priority != null && priority.toString().equals("HIGH")) {
                    int traceCount = RequirementTraceHelper.getRelatedBlocks(req).size()
                                   + RequirementTraceHelper.getRelatedHazards(req).size()
                                   + RequirementTraceHelper.countFMEALinksForRequirement(model, req);
                    if (traceCount < 2) underTraced++;
                }
            }
            if (underTraced > 0)
                recommendations.add(new Recommendation(RecommendationType.REQUIREMENT_TRACEABILITY,
                    underTraced + " high-priority requirement(s) have insufficient traceability (< 2 links)."));
        }

        return recommendations;
    }

    // =========================================================================
    // Private helpers
    // =========================================================================

    private boolean hasFMEAAnalysis(SafetyCriticalBlock block, UnifiedSystemModel model) {
        for (FMEAAnalysis analysis : model.getFmeaAnalysis()) {
            for (FMEAItem item : analysis.getFmeaItems()) {
                if (item.getAnalyzedComponent() == block) return true;
            }
        }
        return false;
    }

    private int countHazardToBlockLinks(UnifiedSystemModel model) {
        int count = 0;
        for (IntegratedHazard hazard : model.getGlobalHazards())
            count += hazard.getRelatedBlocks().size();
        return count;
    }

    private int countFMEAToComponentLinks(UnifiedSystemModel model) {
        int count = 0;
        for (FMEAAnalysis analysis : model.getFmeaAnalysis())
            for (FMEAItem item : analysis.getFmeaItems())
                if (item.getAnalyzedComponent() != null) count++;
        return count;
    }

    private int countFMEAToFailureModeLinks(UnifiedSystemModel model) {
        int count = 0;
        for (FMEAAnalysis analysis : model.getFmeaAnalysis())
            for (FMEAItem item : analysis.getFmeaItems())
                if (item.getFailureMode() != null) count++;
        return count;
    }

    private int countFMEAToHazardLinks(UnifiedSystemModel model) {
        int count = 0;
        for (FMEAAnalysis analysis : model.getFmeaAnalysis())
            for (FMEAItem item : analysis.getFmeaItems())
                count += item.getRelatedHazards().size();
        return count;
    }

    private int estimateSeverity(SafetyCriticalBlock block, BlockFailureMode fm) {
        if (block.getAsilLevel() == ASILLevel.ASIL_D) return 10;
        if (block.getAsilLevel() == ASILLevel.ASIL_C) return 8;
        if (block.getAsilLevel() == ASILLevel.ASIL_B) return 6;
        return 4;
    }

    private int estimateOccurrence(BlockFailureMode fm) {
        double rate = fm.getFailureRate();
        if (rate > 0.001)   return 10;
        if (rate > 0.0001)  return 7;
        if (rate > 0.00001) return 5;
        return 3;
    }

    private UnifiedSystemModel getModel(EObject element) {
        EObject current = element;
        while (current != null) {
            if (current instanceof UnifiedSystemModel) return (UnifiedSystemModel) current;
            current = current.eContainer();
        }
        return null;
    }
}